var navb = document.getElementById("navbar-brand");
navb.setAttribute("style","font-style: oblique;font-family: fangsong;");
var navbt = document.getElementById("navbar-toggler");
navbt.setAttribute("style","text-decoration: none;");
var shop = document.getElementById("shop");
shop.setAttribute("style","text-decoration: none;");
var offcanvasNavbarLabel = document.getElementById("offcanvasNavbarLabel");
offcanvasNavbarLabel.setAttribute("style","color:#ffff;");
var container1 = document.getElementById("container1");
container1.setAttribute("style","background-color: #f8f9fa;");
var col1 = document.getElementById("col1");
col1.setAttribute("style"," PADDING: 200PX  0 150px 50PX;");
var hcol1 = document.getElementById("hcol1");
hcol1.setAttribute("style","padding-left: 50px; font-size: 70px;");
var style = document.getElementById("style");
style.setAttribute("style","padding-top: 11px;text-align: center;background-color: #c35cfeb3; color:#ffff; width: 200px;height: 50px;cursor: pointer;");
var style1 = document.getElementById("style1");
style1.setAttribute("style","text-decoration: none; color: #ffff;");
var container2 = document.getElementById("container2");
container2.setAttribute("style","margin-top: 40px;");
var col2 = document.getElementById("col2");
col2.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER; COLOR: #FFFF;");
var h5 = document.getElementById("h5");
h5.setAttribute("style"," text-align: center;");
var h3 = document.getElementById("h3");
h3.setAttribute("style"," text-align: center;");
var col3 = document.getElementById("col3");
col3.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER; COLOR: #FFFF;");
var h5h = document.getElementById("h5h");
h5h.setAttribute("style"," text-align: center;");
var h3h = document.getElementById("h3h");
h3h.setAttribute("style"," text-align: center;");
var container3 = document.getElementById("container3");
container3.setAttribute("style","margin-top: 90px;");
var section1 = document.getElementById("section1");
section1.setAttribute("style","text-align: center;width: 70%; margin-left: 15%; margin-top: 40px;background-color: #c35cfe99;padding-top: 10px;border-radius: 20px");
var h1h1 = document.getElementById("h1h1");
h1h1.setAttribute("style"," color: #ffff;");
var container4= document.getElementById("container4");
container4.setAttribute("style","margin-top: 100px;");
var row1= document.getElementById("row1");
row1.setAttribute("style","justify-content: center;");
var col4 = document.getElementById("col4");
col4.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3); outline: dashed;width: 300px;height: 401;margin: 10px;");
var h55 = document.getElementById("h55");
h55.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var img= document.getElementById("img");
img.setAttribute("style","padding: 40px;");
var hh= document.getElementById("hh");
hh.setAttribute("style","text-align: center;");
var cc= document.getElementById("cc");
cc.setAttribute("style","text-align: center;");
var dd= document.getElementById("dd");
dd.setAttribute("style","text-align: center;");
var ee= document.getElementById("ee");
ee.setAttribute("style","text-align: center;");
var ff= document.getElementById("ff");
ff.setAttribute("style","text-align: center;");
var gg= document.getElementById("gg");
gg.setAttribute("style","text-align: center;");
var ii= document.getElementById("ii");
ii.setAttribute("style","text-align: center;");
var jj= document.getElementById("jj");
jj.setAttribute("style","text-align: center;");
var kk= document.getElementById("kk");
kk.setAttribute("style","text-align: center;");
var ll= document.getElementById("ll");
ll.setAttribute("style","text-align: center;");
var mm= document.getElementById("mm");
mm.setAttribute("style","text-align: center;");
var nn= document.getElementById("nn");
nn.setAttribute("style","text-align: center;");
var oo= document.getElementById("oo");
oo.setAttribute("style","text-align: center;");
var pp= document.getElementById("pp");
pp.setAttribute("style","text-align: center;");
var aaa= document.getElementById("aaa");
aaa.setAttribute("style","text-align: center;");
var bbb= document.getElementById("bbb");
bbb.setAttribute("style","text-align: center;");
var ccc= document.getElementById("ccc");
ccc.setAttribute("style","text-align: center;");
var ddd= document.getElementById("ddd");
ddd.setAttribute("style","text-align: center;");
var eee= document.getElementById("eee");
eee.setAttribute("style","text-align: center;");
var fff= document.getElementById("fff");
fff.setAttribute("style","text-align: center;");
var ggg= document.getElementById("ggg");
ggg.setAttribute("style","text-align: center;");
var hhh= document.getElementById("hhh");
hhh.setAttribute("style","text-align: center;");
var iii= document.getElementById("iii");
iii.setAttribute("style","text-align: center;");
var jjj= document.getElementById("jjj");
jjj.setAttribute("style","text-align: center;");
var kkk= document.getElementById("kkk");
kkk.setAttribute("style","text-align: center;");
var lll= document.getElementById("lll");
lll.setAttribute("style","text-align: center;");
var mmm= document.getElementById("mmm");
mmm.setAttribute("style","text-align: center;");
var nnn= document.getElementById("nnn");
nnn.setAttribute("style","text-align: center;");
var h56 = document.getElementById("h56");
h56.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h57 = document.getElementById("h57");
h57.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h58 = document.getElementById("h58");
h58.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h59 = document.getElementById("h59");
h59.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h60 = document.getElementById("h60");
h60.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h61 = document.getElementById("h61");
h61.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h62 = document.getElementById("h62");
h62.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h63 = document.getElementById("h63");
h63.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h64 = document.getElementById("h64");
h64.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h65 = document.getElementById("h65");
h65.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h66 = document.getElementById("h66");
h66.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h67 = document.getElementById("h67");
h67.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var h68 = document.getElementById("h68");
h68.setAttribute("style"," BACKGROUND-COLOR: #c35cfe;WIDTH: 60PX;TEXT-ALIGN: CENTER;COLOR: #FFFF;");
var button5 = document.getElementById("button5");
button5.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button6 = document.getElementById("button6");
button6.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button7 = document.getElementById("button7");
button7.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button8 = document.getElementById("button8");
button8.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button9 = document.getElementById("button9");
button9.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button10 = document.getElementById("button10");
button10.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button11 = document.getElementById("button11");
button11.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button12 = document.getElementById("button12");
button12.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button13 = document.getElementById("button13");
button13.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button14 = document.getElementById("button14");
button14.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button15 = document.getElementById("button15");
button15.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button16 = document.getElementById("button16");
button16.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button17 = document.getElementById("button17");
button17.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var button18 = document.getElementById("button18");
button18.setAttribute("style","background:#c35cfe;left: 70%;bottom: 2%;color: #fff;position: relative;");
var div0 = document.getElementById("div0");
div0.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div1 = document.getElementById("div1");
div1.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div2 = document.getElementById("div2");
div2.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div3= document.getElementById("div3");
div3.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div4 = document.getElementById("div4");
div4.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div5 = document.getElementById("div5");
div5.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div6 = document.getElementById("div6");
div6.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div7 = document.getElementById("div7");
div7.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div8 = document.getElementById("div8");
div8.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div9 = document.getElementById("div9");
div9.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div10 = document.getElementById("div10");
div10.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div11 = document.getElementById("div11");
div11.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var div12 = document.getElementById("div12");
div12.setAttribute("style","background-color: #f8f9fa;  box-shadow: 0 10px 15px rgba(0,0,0,0.3);  outline: dashed;width: 300px;height: 401;margin: 10px;");
var img1= document.getElementById("img1");
img1.setAttribute("style","padding: 40px;");
var img2= document.getElementById("img2");
img2.setAttribute("style","padding: 40px;");
var img3= document.getElementById("img3");
img3.setAttribute("style","padding: 40px;");
var img4= document.getElementById("img4");
img4.setAttribute("style","padding: 40px;");
var img5= document.getElementById("img5");
img5.setAttribute("style","padding: 40px;");
var img6= document.getElementById("img6");
img6.setAttribute("style","padding: 40px;");
var img7= document.getElementById("img7");
img7.setAttribute("style","padding: 40px;");
var img8= document.getElementById("img8");
img8.setAttribute("style","padding: 40px;");
var img9= document.getElementById("img9");
img9.setAttribute("style","padding: 40px;");
var img10= document.getElementById("img10");
img10.setAttribute("style","padding: 40px;");
var img11= document.getElementById("img11");
img11.setAttribute("style","padding: 40px;");
var img12= document.getElementById("img12");
img12.setAttribute("style","padding: 40px;");
var img13= document.getElementById("img13");
img13.setAttribute("style","padding: 40px;");
var conte1= document.getElementById("conte1");
conte1.setAttribute("style","margin-top: 90px;");
var conte2= document.getElementById("conte2");
conte2.setAttribute("style","margin-top: 90px;");
var ic1= document.getElementById("ic1");
ic1.setAttribute("style"," padding-left: 40%;margin-bottom: 40px;");
var ic2= document.getElementById("ic2");
ic2.setAttribute("style"," padding-left: 40%;margin-bottom: 40px;");
var ic3= document.getElementById("ic3");
ic3.setAttribute("style"," padding-left: 40%;margin-bottom: 40px;");
var ic4= document.getElementById("ic4");
ic4.setAttribute("style"," padding-left: 40%;margin-bottom: 40px;");
var colf1= document.getElementById("colf1");
colf1.setAttribute("style","    margin-bottom: 40px; margin-top: 20px;");
var colf2= document.getElementById("colf2");
colf2.setAttribute("style","    margin-bottom: 40px; margin-top: 20px;");
var colf3= document.getElementById("colf3");
colf3.setAttribute("style","    margin-bottom: 40px; margin-top: 20px;");
var colf4= document.getElementById("colf4");
colf4.setAttribute("style","    margin-bottom: 40px; margin-top: 20px;");
var footer= document.getElementById("footer");
footer.setAttribute("style","background:#f8f9fa; margin-left: -3%;margin-right: -3%;");
